- name: Assures grafana directories exists
  file: path=/etc/grafana state=directory
  tags:
    - grafana
- name: Assures grafana directories exists
  file: path=/var/lib/grafana/dashboards state=directory
  tags:
    - grafana
- name: Assures grafana directories exists
  file: path=/var/log/grafana state=directory
  tags:
    - grafana

- name: Copy configurations
  template: src="../config/grafana/grafana.ini"
            dest="/etc/grafana/grafana.ini"
            owner=root
            group=root
  tags:
    - grafana
- name: Copy configurations
  template: src="../config/grafana/dashboards.json"
            dest="/var/lib/grafana/dashboards/dashboards.json"
            owner=root
            group=root
  tags:
    - grafana-copy

- name: "Launch Grafana container"
  docker:
    name: grafana
    image: grafana/grafana:4.0.0-beta2
    state: reloaded
    restart_policy: always
    ports:
      - "3000:3000"
    links:
      - influxdb
    volumes:
      - /var/lib/grafana:/var/lib/grafana
      - /etc/grafana:/etc/grafana
      - /var/log/grafana:/var/log/grafana
    env:
      GF_SECURITY_ADMIN_PASSWORD: "{{gf_admin_password}}"
  tags:
    - grafana
